[alpaca-7b]
name="Alpaca, 7B parameters"

[chronos-hermes-13b]
name="Chronos Hermes (13B)"

[deepseek-67b]
name="DeepSeek LLM Chat (67B)"

[gemma-7b]
name="Gemma Instruct (7B)"

[llama-2-7b-chat]
name = "Meta Llama 2, 7b parameters"

[llama-2-13b-chat]
name = "Meta Llama 2, 13b parameters"

[llama-2-70b-chat]
name = "Meta Llama 2, 70b parameters"

[mistral-7b]
name = "Mistral 7B Instruct v0.2"

[mixtral-8x-7b]
name = "Mixtral-8x7B Instruct v0.1 (46.7B)"

[openchat-3_5]
name = "OpenChat 3.5 (7B)"

[stripedhyena-nous-7b]
name = "Together StripedHyena Nous 7B"

[wizardlm-13b]
name = "WizardLM v1.2 (13B)"

[vicuna-13b]
name = "LM Sys Vicuna v1.5 (13B)"

[yi-34b]
name = "01-ai Yi Chat (34B)"
